name: 'Build, deploy, and release'

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-publish-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Build a binary wheel and a source tarball
        run: >-
          python setup.py
          sdist
          bdist_wheel
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
      - id: get_version
        uses: battila7/get-version-action@v2.2.1
      - name: Get release notes
        id: get-release-notes
        uses: release-flow/keep-a-changelog-action/get-release-notes@v1
        with:
          release-version: ${{ steps.get_version.outputs.version-without-v }}
      - name: Display release notes
        run: |
          echo "${{ steps.get-release-notes.outputs.release-notes }}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.get_version.outputs.version-without-v }}
          body: ${{ steps.get-release-notes.outputs.release-notes }}
          draft: false
          prerelease: false
